### ISSUE TITLE
Error when inference 

### ISSUE THREAD

**Issue by Garamda** [pierluigiferrari/ssd_keras#163]
Hi! I really appreciate your implementation of SSD.
I'm using your code to detect concrete crack in crack images.

I finished naive training, and wanted to do inference on new crack image.
but when I do `y_pred = model.predict(input_images)`,

`2018-07-25 06:03:38.736651: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`
pops up in anaconda cmd. 

It can't be only originated from cudnn, because when training, cudnn worked properly.
So I'm suspecting whether my model loaded in `model_path` is wrongly constructed and trained or something else.

Since I can't assure anything, I'll upload the full code for my inference,

```
from keras import backend as K
from keras.models import load_model
from keras.preprocessing import image
from keras.optimizers import Adam
from imageio import imread
import numpy as np
from matplotlib import pyplot as plt

from models.keras_ssd300 import ssd_300
from keras_loss_function.keras_ssd_loss import SSDLoss
from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
from keras_layers.keras_layer_DecodeDetections import DecodeDetections
from keras_layers.keras_layer_DecodeDetectionsFast import DecodeDetectionsFast
from keras_layers.keras_layer_L2Normalization import L2Normalization

from ssd_encoder_decoder.ssd_output_decoder import decode_detections, decode_detections_fast

from data_generator.object_detection_2d_data_generator import DataGenerator
from data_generator.object_detection_2d_photometric_ops import ConvertTo3Channels
from data_generator.object_detection_2d_geometric_ops import Resize
from data_generator.object_detection_2d_misc_utils import apply_inverse_transforms

%matplotlib inline

img_height = 300
img_width = 300

model_path = 'C:\\Users\\user\keras\ssd_keras\ssd300_pascal_07+12_epoch-08_loss-0.2683_val_loss-0.2423.h5'

ssd_loss = SSDLoss(neg_pos_ratio=3, n_neg_min=0, alpha=1.0)

K.clear_session() # Clear previous models from memory.

model = load_model(model_path, custom_objects={'AnchorBoxes': AnchorBoxes,
                                               'L2Normalization': L2Normalization,
                                               'DecodeDetections': DecodeDetections,
                                               'compute_loss': ssd_loss.compute_loss})

orig_images = [] # Store the images here.
input_images = [] # Store resized versions of the images here.

img_path = 'C:\\Users\\user\Desktop\crack.jpg'

orig_images.append(imread(img_path))
img = image.load_img(img_path, target_size=(img_height, img_width))
img = image.img_to_array(img) 
input_images.append(img)
input_images = np.array(input_images)

y_pred = model.predict(input_images)    #ERROR HERE
```

If you think this issue is just about my cudnn or nvidia software problem, then I'll strive by myself.
However, if you have seen any similar cases like mine, would you share your idea?

I appreciate it.

**Comment by pierluigiferrari** [comment]
I can't help with that one, unfortunately. I'd say this is a question for Google / StackOverflow.

**Comment by Garamda** [comment]
@pierluigiferrari I solved it! Thanks

**Comment by Cabbagehust2507** [comment]
> @pierluigiferrari I solved it! Thanks

I had the same error. How did you solve it? Thank you so much.
